### ISSUE TITLE
XMLHttpRequest Method

### ISSUE THREAD

**Issue by n2westman** [Countly/countly-sdk-web#1]
Responses from server generate a CORS error, I think that's because the method of choice is a GET instead of a POST

**Comment by ar2rsawseen** [comment]
@n2westman I think both GET and POST will generate CORS errors if
1) The requests are not made to the same domain
2) Server does not allow CORS requests

So the CORS was enabled in Countly 15.03 server, previous to that version it was disallowed, unfortunately for now it would mean it is unavailable for Countly cloud, but we are working on that.

**Comment by ar2rsawseen** [comment]
CORS is now enabled on the Countly Cloud, if you are using your own server, then you would need to upgrade to latest version.

Please reopen the issue if problem persists ;)
