### ISSUE TITLE
Do you offer a notification service for web

### ISSUE THREAD

**Issue by yehia67** [Countly/countly-sdk-web#100]
Hello,
I am trying to implement a push notification service for on-premise deployment. Does countly-sdk-web offer that service? I found you mentioning the notification feature but I didn't found it on examples directory. Do you offer notification service for nodejs web app?

**Comment by ar2rsawseen** [comment]
Hello
nope, only push notifications for mobile apps

**Comment by yehia67** [comment]
Okay thanks.
I appreciate your fast reply.
