### ISSUE TITLE
track_links & track_clicks didn't track dynamic added dom elements

### ISSUE THREAD

**Issue by jianglinchun** [Countly/countly-sdk-web#11]
If we had a ajax request and append some dom elements to the document.
The track_links & track_clicks will not be triggered on those newly added elements.

**Comment by ar2rsawseen** [comment]
Currently you can call track_links or track_clicks method and provide parent element of changed content for example to add those new elements to registry

But I will try to think on better solution

**Comment by ar2rsawseen** [comment]
Are you sure track_clicks is not working, from the code it should work, cause it listens to bubbled evens on the document level

**Comment by jianglinchun** [comment]
tested under chrome many times. Pls check.

**Comment by ar2rsawseen** [comment]
This issue should be fixed on development branch by https://github.com/Countly/countly-sdk-web/commit/c324f3d737d4ab54130e1015ee52825e1d52460f

Note if you want to try development branch, then it currently does not parse user agent and does not send all metrics to server, metrics are post filled by web plugin on server side (which require some modifications on server)

Will close issue after release, when development branch is merged

**Comment by jianglinchun** [comment]
I'd review the fix. And I found that closest was use to fix this issues. Please make sure compatible problems.

http://stackoverflow.com/questions/18663941/finding-closest-element-without-jquery

Btw: countly may focus on App statics tracking and analytic. But web/wap/h5 still a important entrance.

**Comment by jianglinchun** [comment]
I had test the latest branch and it works.

**Comment by ar2rsawseen** [comment]
Yes, there is a polyfil for when it is not available:
https://github.com/Countly/countly-sdk-web/commit/684e4159e2d4bd83a0abcfd18548a26c5bb4633d

So it should be compatible with older systems too
