### ISSUE TITLE
Screen.width & screen.height have compatible problems.

### ISSUE THREAD

**Issue by jianglinchun** [Countly/countly-sdk-web#12]
I'd found those code below:
`//getting resolution
        if (screen.width) {
            var width = (screen.width) ? screen.width : '';
            var height = (screen.height) ? screen.height : '';
            metrics._resolution = '' + width + "x" + height;
        }`

I found exactly the problem why metrics._resolution return wrong value from ios or android devices:

screen.width/screen.height returns logical resolution(dpi) on iOS while android return physical resolution(pix) on Android:
http://stackoverflow.com/questions/6850164/get-the-device-width-in-javascript

So metrics._resolution should be improved. Cause we developers can't argue the resolution's value with marketing & biz guys. And the boss. So…… I'ts a choice and a compatible problem……

**Comment by ar2rsawseen** [comment]
So which way is correct in your opinion? iOS or Android?

**Comment by ar2rsawseen** [comment]
Would something like this work?
http://stackoverflow.com/a/24018397

**Comment by jianglinchun** [comment]
Yes. Something like that. Please do more test.

**Comment by ar2rsawseen** [comment]
Here is the current fix
https://github.com/Countly/countly-sdk-web/commit/280bbae7f8fd629fc16ca3a2befd27efcc2dc866

unfortunately it seems some Android devices also report logical dimensions, unfortunately currently we have no way of detecting them and processing them correctly.

**Comment by jianglinchun** [comment]
@ar2rsawseen Thank you so much. I though it's better now. :)
