### ISSUE TITLE
Element is Not Defined With  React Integrations

### ISSUE THREAD

**Issue by Vaysi** [Countly/countly-sdk-web#128]
Hey Guys , Thanks For Your Analytics System.
I Have a Problem in Web Version . I Use React.js & Next.js With Typescript And I'm Trying to Use WithEffect Sample But I Keep Getting This Error : ReferenceError: Element is not defined at ..\node_modules\countly-sdk-web\lib\countly.js:3190:5
What is This Error About ?

**Comment by ar2rsawseen** [comment]
Hello,
I think it is all related to this, right?
https://github.com/Countly/countly-sdk-web/pull/121

Currently not sure, which would be the right solution, so any suggestions are welcome :)
