### ISSUE TITLE
Ignore only javascript enabled search bots

### ISSUE THREAD

**Issue by karthilxg** [Countly/countly-sdk-web#13]
Do we really need to ignore all the search bots with [this](https://github.com/Countly/countly-sdk-web/blob/ede6cdf0301a4a3806bb56f9654233dc104a0128/lib/countly.js#L41) regex or is it just required to ignore the bots which has Javascript enabled, if the JS is disabled `countly.js` sdk will not be loaded anyways. Any thoughts ?

``` Javascript
searchBotRE = /(nuhk|Googlebot|Yammybot|Openbot|Slurp|MSNBot|Ask Jeeves\/Teoma|ia_archiver|bingbot|Google Web Preview|Mediapartners-Google|AdsBot-Google|Baiduspider|Ezooms|YahooSeeker|AltaVista|AVSearch|Mercator|Scooter|InfoSeek|Ultraseek|Lycos|Wget|YandexBot|Yandex|YaDirectFetcher|SiteBot|Exabot|AhrefsBot|MJ12bot|TurnitinBot|magpie-crawler|Nutch Crawler|CMS Crawler|rogerbot|Domnutch|ssearch_bot|XoviBot|netseer|digincore|fr-crawler|wesee|AliasIO)/,
```

**Comment by ar2rsawseen** [comment]
You are right, if bot is not javascript enabled, currently there would be no point of ignoring it, but

1) Do you have a list or know which bots are javascript enabled and which are not?
2) Would you follow up all the updates, if some simple bot gets upgraded to javascript enabled bot
3) Would making this regex smaller would really improve sdk?

Considering all the three points above we decided to have this list of bots, but if you have any input on those three points, I am all ears :)
