### ISSUE TITLE
[Question] Support Counlty for multi-page web apps (MVC, ...) ?

### ISSUE THREAD

**Issue by khong07** [Countly/countly-sdk-web#15]
Hi,

I would like to ask you about the support of Countly for multi-page web apps like MVC web app

As I could see in the code, it isn't 100% for a multi-page web app.

For example, we cannot use `track_sessions` because everytime we arrive on a page, it will consider to a session. We can call method `begin_session` on a page but cannot call method `session_duration` or `end_session` on other page without calling `begin_session` first.

In additional, is there some way to make `heartBeat()` public? That we can call it manually instead of waiting for x (ms).

Regards,

**Comment by ar2rsawseen** [comment]
Hello,
that is completely ok to call begin_session on each page view, server will ignore if there is too little time between end_session and begin_session (like 15 second in default configuration). So it should work normally with multi page websites too.

In the future we are thinking on moving to cookie based session management.

About exposing heartbeat, then in 17.05 we exposed all internal methods through _internal namespace, for plugins to be able to extend sdk functionlity and reuse methods

https://github.com/Countly/countly-sdk-web/blob/master/lib/countly.js#L1678-L1706

So you should be able to call

```
Countly._internals.heartBeat();
```

**Comment by khong07** [comment]
:+1: that's great, thank you.
