### ISSUE TITLE
Failed query loops forever

### ISSUE THREAD

**Issue by n2westman** [Countly/countly-sdk-web#2]
On a failed req, countly will loop indefinitely. Should have some number of allowed failures per req!

```
if(requestQueue.length > 0){
			var params = requestQueue.shift();
			log("Processing request", params);
			sendXmlHttpRequest(params, function(err, params){
				log("Request Finished", params, false);
				if(err){
					requestQueue.unshift(params);
					store("cly_queue", requestQueue, true);
				}
			});
			store("cly_queue", requestQueue, true);
		}
```

**Comment by ar2rsawseen** [comment]
Hello,
do you mean
1) SDK generates request that always fails and thus can't get past it, which means we should fix the bug that generates failed request

or

2) When server is off then all request fails and SDK retries request too often, in which case we should implement a timeout

but in both cases we can't simply discard request after specific amount of failures, cause that would mean losing data.

**Comment by n2westman** [comment]
The second of the too... I think a timeout would be a good idea!

**Comment by ar2rsawseen** [comment]
Added 60 second cooldown after failed requests in https://github.com/Countly/countly-sdk-web/commit/a87ccb121b48b05ad11290d660907597ed54e61f

Thanks for suggestion ;)
