### ISSUE TITLE
Events have wrong device_id after using change_id

### ISSUE THREAD

**Issue by mt-ronkorving** [Countly/countly-sdk-web#22]
If I'm not mistaken, I just noticed that when you call `Countly.change_id(newDeviceId)`, any events still in the queue will be attributed to `newDeviceId`.

`end_session` gets immediately invoked, which pushes an event straight to the `requestQueue`. But the events in `eventQueue` are ignored and will be sent in the next heartbeat, with the *new* device_id.

IMHO the only correct behaviors would be to (1) either ensure the whole remaining queue is sent out first, or (2) discard the queue.
The problem with (2) is that there is no way at the moment for me to detect that this is about to happen if I were to call `change_id`, so I can't anticipate the discarding of events and take action to prevent that from happening.

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/Countly/countly-sdk-web/commit/fa0efd25b10cd2fa435036fa59dd55ae3eb6bd20
