### ISSUE TITLE
New device id every load

### ISSUE THREAD

**Issue by carlgrundberg** [Countly/countly-sdk-web#29]
Hi, I'm trying out Countly and has a local setup running. When trying out the web tracking I noticed the dashboard showed a new user and session everytime a refreshed the page.  The device id in local storage also got a new value every time. 

When debugging the code it turned out the stored device id (plain string) could not be parsed by JSON.parse. The exceptions is caught which sets the data to null.  The result is a newly generated device id. 

https://github.com/Countly/countly-sdk-web/blob/d5effb85d41ace6262ae439b61a504548b186e71/lib/countly.js#L2155

Looking at the history i guess it worked earlier because you didn't set the data to null in the catch clause.

I didn't find any other issue about this but it should be really critical?

**Comment by ar2rsawseen** [comment]
Hello,
you are correct and this is critical, fixed and published new minor npm version

**Comment by ar2rsawseen** [comment]
For the reference, added specific test cases to cover this situation and prevent from happening in future:
https://github.com/Countly/countly-sdk-web/pull/30
