### ISSUE TITLE
version inconsistencies

### ISSUE THREAD

**Issue by SgtPooki** [Countly/countly-sdk-web#350]
countly-web-sdk currently has a different package.json version than the published version, causing `npm outdated` to gripe:

```bash

╰─ ✔ ❯ npm outdated
Package             Current   Wanted   Latest  Location                      Depended by
@esbuild/linux-x64  MISSING  0.16.17  0.16.17  -                             ignite-metrics
countly-sdk-web     22.06.4   22.6.4   22.6.4  node_modules/countly-sdk-web  ignite-metrics
```

see 

- https://github.com/Countly/countly-sdk-web/blob/1c72a3b5d4c1e66031e3ecc5779adfe030ab21e0/package.json#L3
- https://www.npmjs.com/package/countly-sdk-web?activeTab=versions

**Comment by ArtursKadikis** [comment]
Hello, looks like "npm" might not be accepting version numbers with a leading "0". We will look into this.

**Comment by turtledreams** [comment]
This issue has been mitigated since version [23.2.2](https://github.com/Countly/countly-sdk-web/releases/tag/23.2.2)
