### ISSUE TITLE
It is not possible to cancel the timed event

### ISSUE THREAD

**Issue by yevhenii-username** [Countly/countly-sdk-web#359]
Currently, I am not available to cancel the _start_event_ action, just only _end_event_ with sending data to the server. 

### Example. 

I want to track how much time the user spending to create a new entity in my application. 

The user starts creating an entity, I run _start_event_
The user ends to create an entity. I run _end_event_

If the user starts creating and decides to cancel creating and close the feature.

### Expected 

The event will skip. And next time the event time will start again.

### Actually 

The event stays in the array and the next time when the user starts this flow the event time be added to the previously canceled flow

**Comment by ArtursKadikis** [comment]
Thank you for bringing this up, we will look into adding the ability to cancel timed events.

**Comment by ruslanshelar** [comment]
Hello there! It is a very important and useful ability to cancel an event. Do u plan to implement it and when? @ArtursKadikis

**Comment by ArtursKadikis** [comment]
Hello, we are planning on implementing this. Most likely in the next few weeks.

**Comment by turtledreams** [comment]
Hi, we have added the feature to cancel timed events in this release (https://github.com/Countly/countly-sdk-web/releases/tag/22.06.5). Thank you for bringing this up. You can reach the updated documentation from here: https://support.count.ly/hc/en-us/articles/360037441932#timed-events
