### ISSUE TITLE
Feedback widget  is not displayed when it is set to appear on all pages

### ISSUE THREAD

**Issue by raulotaolea** [Countly/countly-sdk-web#36]
When you establish through the menu option `Engagement -> Rating -> FEEDBACK WIDGETS` on Countly Community Edition Server, and create a new widget configuring that the widget must be seen on all pages, the widget is not displayed.

**Comment by frknbasaran** [comment]
Hello @raulotaolea 

I checked the problem you mentioned above, yes there is a bug which may cause this problem in some cases. I created a fix. Also I noticed your PR too, thank you for your time and helpful feedback but this problem requires some minor changes too in our web sdk. I'm working on it. Will be fixed asap.

Thanks for your help and understanding.

**Comment by ar2rsawseen** [comment]
Merged and released
