### ISSUE TITLE
Session duration issues

### ISSUE THREAD

**Issue by 8pig** [Countly/countly-sdk-web#381]
Why can't I count the session duration after initialization? What is the data format? Is it convenient to say?  I want to customize data reporting, but I can't count the time。  

Thank you.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/25922412/222400053-6fdb525b-7c33-4004-9f9d-ed60e573ed64.png">

```javascript
        //initializing countly with params
        Countly.init({
            app_key: 'key', //your app key
            url: 'here', //your server goes here
            debug: true
        });
        Countly.begin_session();

```

**Comment by ArtursKadikis** [comment]
Hello. 
What do you mean with "Why can't I count the session duration after initialization"? "Where" and "why" would you want to count something?
"What is the data format?" - what is the data format where? In the dashboard or in the SDK?
" I want to customize data reporting, but I can't count the time。" In what way do you want to customize the data reporting?

**Comment by 8pig** [comment]
Yes, I found the point and data statistics logic of the count report. Now the custom report has been implemented. Thank you
