### ISSUE TITLE
Shipping Countly In a WebWorker Context

### ISSUE THREAD

**Issue by whizzzkid** [Countly/countly-sdk-web#382]
Hello Team

We are using countly (wrapped inside `[ignite-metrics](https://github.com/ipfs-shipyard/ignite-metrics/)`) in `[ipfs-companion](https://github.com/ipfs/ipfs-companion)`. We are in process of migrating to Chrome manifest v3 and are facing issues with bundling `countly-sdk-web` with respective shims and browserfied counterparts in a `webworker` context.

Manifest V3 expects the background page to be a `webworker` which means no access to DOM/window objects and using only `fetch` api to request resources. However, `countly-sdk-web` does not ship with tree-shakable modules, which would remove direct dependency on `window` object. As we're not using all the features of the SDK, and it gets bundled in it's entirety.

I see #75 wanted to tackle something along those lines but has not seen much traction. Any guidance on this would be appreciated. In the meantime, we've resolved to including the entire sdk on pages with window context.

Thanks

**Comment by BigLep** [comment]
@ArtursKadikis : is there any sense of timeline for addressing this?  Some info (even if rough) is better than none.  For example would this happen in a month, in 2023Q2, by end of the year?

I'm asking so we can plan our work accordingly.  I'd ideally like to be staying on countly SDKs but given the last [shared  dates in March](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/) of Chrome webstore rejecting extensions that aren't MV3 compatible, we may have to roll our own client SDK.

**Comment by SgtPooki** [comment]
@ArtursKadikis the main thing I think many users would like to see is a version of the countly sdk that works in both node and the web. i.e. an ESM module, that doesn't include side-effects (not kicking off the IIFE). 

However, for the sake of getting this resolved; Simply removing the IIFE, and using dependency injection should resolve many of our current problems as well as future issues without being too much of a burden on your team.

**Comment by SgtPooki** [comment]
@ArtursKadikis any update on the removal of the window object and making the web SDK more webworker friendly?

**Comment by turtledreams** [comment]
@SgtPooki Unfortunately, other priorities took over, and we did not have time to focus on web SDK for a while. Currently, we are looking into creating a new JS SDK that would be able to work in broader contexts.
Which features are you currently using?

**Comment by turtledreams** [comment]
Hi,
We have modified the SDK to be Web Worker friendly with the latest release (23.12.0). Currently, it seems to be working with non-Module Workers. However, as you also mentioned in your implementation, automatic tracking is not working (like for sessions, views, clicks, etc) as it depends on the window object.

Also, we extended the storage methods so you can provide your own. If you encounter any issues, please let us know.

Current documentation on the topic: https://support.count.ly/hc/en-us/articles/360037441932-Web-analytics-JavaScript-#h_01HH1BABFQ48FKWGJCX9HFMKW8

**Comment by ArtursKadikis** [comment]
Hello,

Looks like it should be working in a web worker context. Will be closing this for now.
We can reopen in case there are any issues related to it.
