### ISSUE TITLE
Device ID not used for the queued queries when disabling offline mode

### ISSUE THREAD

**Issue by faouzioudouh** [Countly/countly-sdk-web#383]
## Summary
We are using counlty on guarded app, where users need to authenticate to use the app.
In order for countly to not duplicate profiles we use `user.id` as the `countly.device_id` after the user is logged in

## Steps:

1. init Countly with `offline_mode: true`
2. User authenticate to our app
3. `Countly.disable_offline_mode(user.id)`
4. `Countly.user_details(user)`

After disabling `offline mode`, countly will send all queued queries to server, we were expecting all queries to have the `device_id` we set at step #3, but instead we see few queries (`remote_config` and `user_details`) submitted with temporary device Id `[CLY]_temp_id`

### Query 1
![Screenshot 2023-03-14 at 17 44 23](https://user-images.githubusercontent.com/4366612/225081310-da2f79c5-8d4e-4fe8-b638-de354670dfa8.png)

### Query 2 
![Screenshot 2023-03-14 at 17 44 30](https://user-images.githubusercontent.com/4366612/225081316-01f6137c-1814-455d-a0c4-718db30a3ea4.png)

### Query 3
![Screenshot 2023-03-14 at 17 44 38](https://user-images.githubusercontent.com/4366612/225081319-8b855d04-2b63-4ba7-b3e8-a1c00e3df264.png)

**Comment by turtledreams** [comment]
Hi, thank you for bringing this up, things should be working with the recent release (https://github.com/Countly/countly-sdk-web/releases/tag/23.02.1).
