### ISSUE TITLE
Comments and email on feedback widget are not saved on server

### ISSUE THREAD

**Issue by raulotaolea** [Countly/countly-sdk-web#41]
When completing the feedback form and sending it successfully, I can see the ratings on server, but not the comments or the emails.

**Comment by frknbasaran** [comment]
Hello

What is your Countly version?

Thanks for your reporting.

**Comment by raulotaolea** [comment]
Hi there !

My version is **Countly Community Edition v18.08.2**

**Comment by frknbasaran** [comment]
Hello again, thanks for quick reply :)

Some users were reported similar problem to us and we've applied some fixes to new versions of Countly. Is it possible to update your Countly instance to latest version? 

https://github.com/Countly/countly-server/releases/tag/v19.02.1

If you still continue see this problem, we can inspect your case specially again. 

Thanks again.

**Comment by raulotaolea** [comment]
Thanks @frknbasaran!
I will update it to check if the rest of the data is saved successfully.

**Comment by baptisteArnaud** [comment]
Hello,
It still doesn't work with `v19.02.1` for me
