### ISSUE TITLE
Can not work with salt.

### ISSUE THREAD

**Issue by leewenbil** [Countly/countly-sdk-web#469]
If set the salt, the Countly can not work. The code likes the following:
`Countly.init({
                    app_key: ...,
                    url: ...,
                    salt: ...,
                });`

**Comment by leewenbil** [comment]
BTW, I have done some improvements on the branch at https://github.com/leewenbil/countly-sdk-web/tree/add-salt, so it can work when set up the salt. You can also reach the minified SDK [countly.with.salt.min.js](https://github.com/leewenbil/countly-sdk-web/blob/add-salt/lib/countly.with.salt.min.js)

**Comment by ArtursKadikis** [comment]
Hello,
"If set the salt, the Countly can not work. "
I would assume that countly still works, but it doesn't have the salt feature.
This is by design as it is not really possible to have it in a secure way in the browser. We don't plan on adding the salt feature to the web SDK.

I did look at the changes done in your branch. in total in has ~12500 lines changed.  There is no way of telling what specific changes you did because you changed the whole formatting.

**Comment by leewenbil** [comment]
> Hello, "If set the salt, the Countly can not work. " I would assume that countly still works, but it doesn't have the salt feature. This is by design as it is not really possible to have it in a secure way in the browser. We don't plan on adding the salt feature to the web SDK.
> 
> I did look at the changes done in your branch. in total in has ~12500 lines changed. There is no way of telling what specific changes you did because you changed the whole formatting.

Thank you for your feedback. I got it. I have some change and crate the [pull request](https://github.com/Countly/countly-sdk-web/pull/470) you can review the code(not format). 
BTW, why do I do the change? We know that If salt on Countly server is set, all requests would be checked for the validity of &checksum field before being processed. So need to set exactly the same salt on the on the SDK side, then salt to be used for calculating checksum of request data, which will be sent with each request using &checksum field.

**Comment by leewenbil** [comment]
@ArtursKadikis would you please check this? Thank you

**Comment by ArtursKadikis** [comment]
Hello, @leewenbil , I answered in the PR
