### ISSUE TITLE
China map is displayed incorrectly

### ISSUE THREAD

**Issue by leewenbil** [Countly/countly-sdk-web#471]
China map is displayed incorrectly, because Taiwan is not included. Internationally, we know the one-China principle, China map must include Taiwan. 
<img width="1582" alt="WeChatWorkScreenshot_056c5676-e823-4e7e-90bc-9cc2af693ef5" src="https://github.com/Countly/countly-sdk-web/assets/3294022/052417dc-f744-432c-9d7c-3f2cc268e067">

**Comment by ArtursKadikis** [comment]
Hello,

This repository is specifically for discussing technical issues related to this SDK.

For dashboard related questions and anything else, please go to our discord:
https://discord.gg/countly
