### ISSUE TITLE
After using "opt_out" method, "opt_In" method does not work properly without reloading the browser screen.

### ISSUE THREAD

**Issue by pavelPX** [Countly/countly-sdk-web#482]
Hi everyone! 

I faced with a problem in React Web App, that after using the "opt_out" method to disable all tracking in the application, I try to resume tracking again with "opt_in" method, but it doesn't work without reloading the current tab in browser.

Does it proper behaviour? 
  
Lib: Web analytics (JavaScript) "countly-sdk-web": "20.11.1"

**Comment by turtledreams** [comment]
Hi @pavelPX,
Yes, the behavior you described is correct. Those methods will take effect at the next init. While not deprecated, they are now considered legacy methods. If you need a method to stop/start tracking for some or all features, you will need to use 'consent,' its successor. (Its documentation for your SDK version is here: https://support.count.ly/hc/en-us/articles/4408793793689-Web-analytics-JavaScript-20-11#h_01HBKRGY4GK0Z16S72V40G714X)

Also, one thing to mention is that your SDK version is very old. Using that version would prevent you from receiving any updates and fixes. It is also not recommended if your server version is newer (https://support.count.ly/hc/en-us/articles/4408793793689-Web-analytics-JavaScript-20-11#h_01HBKRGY4GK0Z16S72V40G714X). Our recommendation is for you to update the SDK to the latest version after going through the release notices for any breaking changes (https://github.com/Countly/countly-sdk-web/releases).

**Comment by pavelPX** [comment]
Thank you so much!
________________________________
