### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by deliriousrhino** [Countly/countly-sdk-web#5]
When using the SDK I am getting CORS errors
```
XMLHttpRequest cannot load
'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by deliriousrhino** [comment]
Duplicate of #1 ;)

**Comment by ar2rsawseen** [comment]
So everything is ok?
Basically server should accept any origin and I think all API requests do, if not open issue on countly-server ;)

**Comment by deliriousrhino** [comment]
Yeah is ok looks like we just need to upgrade our server

**Comment by SatishChandraPalakoti** [comment]
I am experiencing this in the version 20.+. Can someone help ?

**Comment by ar2rsawseen** [comment]
Hello,
check headers on server in Countly dashboard -> top cog -> Configurations -> Security -> Additional API HTTP Response headers
it should contain Access-Control-Allow-Origin: *

**Comment by kamrul10** [comment]
api_additional_headers: "X-Frame-Options:deny\nX-XSS-Protection:1; mode=block\nAccess-Control-Allow-Origin:*"
this configuration is there but still showing  cors issue
countly version is 24.05.2

**Comment by ar2rsawseen** [comment]
Hello @kamrul10 
can you show us what error and response from server you get in your website network tab?

**Comment by kamrul10** [comment]
Hi @ar2rsawseen 
Thanks for the reply 👍
This issue got resolved 
It was not countly issue

**Comment by ar2rsawseen** [comment]
No problem, glad it was resolved :)
