### ISSUE TITLE
Countly.user_details

### ISSUE THREAD

**Issue by deliriousrhino** [Countly/countly-sdk-web#6]
I am sending user details via  Countly.user_details we are self hosted with Countly Enterprise 14.06.
I don't see these details come thought to the admin portal. 
Where should I see them? Or do we need to upgrade
```
var user = {
                    "name": venue.name,
                    "organization": account.businessName,
                    "custom": {
                        "venueId": venue.id,
                        "accountId": account.id,
                        "state": venue.state,
                        "postcode": venue.postcode
                    }
                }
                Countly.user_details(user);
```

Debug log
```
Request Finished
{"user_details":"{\"name\":\"Kahli’s Test Restaurant\",\"organization\":\"Kahli's Test Restaurant\",\"custom\":{\"venueId\":30,\"accountId\":\"bcba31a3-c6ef-40d6-bd1a-f922329774e6\",\"state\":\"NSW\",\"psotcode\":\"2103\"}}","app_key":"2a9b7f95a5fa3c7270a4925495bc83881785b4d0","device_id":"4ea3714c-7aa7-4cce-8c77-ee60d84fd492","timestamp":1441608057,"hour":16,"dow":1}
false
```

**Comment by ar2rsawseen** [comment]
Yes request is delivered correctly, your server does not collect such information.
User profiles were introduced with new core supporting plugins (meaning at least 15.03), you would need to upgrade to new version which would require clean install, more information here:
http://resources.count.ly/docs/upgrading-countly-server

**Comment by gorkem-cetin** [comment]
@deliriousrhino please send an email to hello at count.ly and we'll send you the latest update.
