### ISSUE TITLE
Recommended "latest" jsdelivr file is not the latest.

### ISSUE THREAD

**Issue by dimaqq** [Countly/countly-sdk-web#64]
Caveat: I could be very much confused

I've followed https://code.count.ly/integration-web.html and picked `jsdelivr` option, which resulted in a blob of javascript that included the following link:

https://cdn.jsdelivr.net/countly-sdk-web/latest/countly.min.js
file size: 18191 bytes
sha512: 54bf53addedf1661ed247702f9ece2867b4d44438737c5a7fb12e4935cbfd0ae589ffa091dbda7237cce7e0ca6cfeccc6388d3e9e9490cf470b301ed99f3778b
I don't know what version that is, but the code is clearly countly.

However, if I go to https://www.jsdelivr.com/package/npm/countly-sdk-web it has this link:
https://cdn.jsdelivr.net/npm/countly-sdk-web@20.4.0/lib/countly.min.js
file size: 34147
sha512: 1c5e334e26b3a330fa24dfab3edf7ba78a5cb401c8a8e8b1c1c9aaa41841fe661420453b1ff65d104bb553385e3cda961442f3c84a6bad0cfbc6a293379947c2

Diff'ing the beautified files, there are quite a lot of differences, for example `.passed_data.purpose` which according to git blame is 2 years old with the commit log stating "async load for umd".

**Comment by ar2rsawseen** [comment]
Yes, as I see jsdeliver url format changed, so I updated it on code.count.ly
It should really load latest script now :)
Thank you for reporting
