### ISSUE TITLE
Specific consent for remote config

### ISSUE THREAD

**Issue by jacknewberry** [Countly/countly-sdk-web#65]
## Request:
- The ability to turn on remote configuration without any other features.

## Use case:
I plan to use Countly to provide remote configuration. I also take GDPR consent for analytics. I want to be able to turn on remote config without enabling any analytics.

Currently consent can be recorded for a fine-grained range of analytics collection.
`["sessions", "events", "views", "scrolls", "clicks", "forms", "crashes", "attribution", "users", "star-rating", "location", "apm"]`
http://countly.github.io/countly-sdk-web/countly.js.html#line103

Consent for remote config does not have a named feature. Instead it is assumed when consent has been added for at least one feature.
http://countly.github.io/countly-sdk-web/countly.js.html#line999

## Suggestion:
- A new consent feature "config" be added to the list of available features.
- This consent be used when providing remote config, instead of `Countly.check_any_consent()`.

## Workaround:
```ts
Countly.group_features({
  config: ["unrecognised feature to allow remote config"],
})
Countly.add_consent("config")
```

**Comment by ar2rsawseen** [comment]
Hello
sure technically this is possible
Just thinking logically, RemoteConfig is not tracking (as it itself is not sending any information, but rather receiving it), so that was the initial idea behind not adding it :)

But adding @ArtursKadikis to provide insight, since it is his decision to put this in all SDKs or not :)

**Comment by jacknewberry** [comment]
Thank you for a quick response. 
Yes, I agree RemoteConfig is not tracking. This is why I want to be able to turn it on even if the user has not consented to tracking.

It seems like at the moment it is only possible to have remoteConfig if you also have some tracking.

**Comment by jacknewberry** [comment]
Hello @ArtursKadikis any movement on this? It seems like a piece of config that is missing, and would be straight forward to add.

**Comment by ar2rsawseen** [comment]
Hello,
sorry for delay, yes we are going with that for next release :)

**Comment by ar2rsawseen** [comment]
This was added here: https://github.com/Countly/countly-sdk-web/commit/9f8a08b69b76e6227e2c008960ff08ded2f836f4
