### ISSUE TITLE
browser identify should be imporved

### ISSUE THREAD

**Issue by jianglinchun** [Countly/countly-sdk-web#9]
I'd found some of those browser in countly.
![_20160825135311](https://cloud.githubusercontent.com/assets/491408/17958311/5877829e-6acb-11e6-916a-de527b3953d5.png)

**Comment by ar2rsawseen** [comment]
Yes, the sdk part parser is kind of bad, so we are moving to server side user agent parser and doing some tests right now, will let you know when we moved
